export * from './contact/Contact';
export * from './home/Home';
export * from './pdf/Pdf';
export * from './profile/Profile';
export * from './settings/Settings';
export * from './splash/Splash';
export * from './videos/Videos';
export * from './webview/Webview';
export * from './work-xp/WorkXP';
