export enum ScreenNames {
  HOME = 'HomeScreen',
  PDF = 'PDFScreen',
  SETTINGS = 'SettingsScreen',
  SPLASH = 'SplashScreen',
  VIDEOS = 'VideosScreen',
  VIDEO = 'VideoScreen',
  CONTACT = 'ContactScreen',
  MEET = 'MeetScreen',
  PROFILE = 'ProfileScreen',
  WORK_XP = 'WorkExperienceScreen',
  WORK_XP_DETAILS = 'WorkExperienceDetailsScreen',
  EDUCATION = 'EducationScreen',
  WEBVIEW = 'WebViewScreen',
}
